baseURL = "https://bamshi.dev/"
languageCode = "en-us"
title = "Bamshi | Dev Portfolio"
theme = "risotto"

[params]
  noindex = false

[params.theme]
  palette = "tokyo-night-dark"

[params.about]
  title = "Bamshi"
  description = "Software Developer | Java, Python, R"
  logo = "💻"

[[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/ahmottie"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

[markup.goldmark.renderer]
  unsafe = true