name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/ahmottie.github.io
            git pull origin main
            /home/a_mottie25/.bun/bin/bun install
            /home/a_mottie25/.bun/bin/bun run build
            sudo /usr/bin/systemctl restart bamshi-site